### ISSUE TITLE
GCI Task: RUN THE VERTEX-GRADEL-SIMPLE PROJECT

### ISSUE THREAD

**Issue by vicens-aniol** [jboss-outreach/vertx-gradle-simple#11]
# GCI Task: RUN THE VERTEX-GRADEL-SIMPLE PROJECT
#### forked project
![](https://image.ibb.co/mhXinw/Captura_1.png)

#### cloned project
![](https://image.ibb.co/b1jJLG/Captura_2.png)

![](https://image.ibb.co/hUrLZb/Captura_3.png)

##### with Eclipse
![](https://preview.ibb.co/nq4WPb/Captura_4.png)

![](https://image.ibb.co/iczLHw/Captura_5.png)

**Comment by garg-anuj** [comment]
Have you tries to run it multiple instances. You are having port not available exception. Either change the port at https://github.com/jboss-outreach/vertx-gradle-simple/blob/master/src/main/java/io/vertx/example/HelloWorldEmbedded.java#L16 or close other exwcutions

**Comment by Ani2004** [comment]
Now I UPDATED the port to 8000

**Comment by SachinRammoorthy** [comment]
Now that the task is complete, perhaps you could close this issue?

**Comment by vicens-aniol** [comment]
Issue Closed
